# CI/CD pipeline to build, test and deploy the application on Docker hub as Docker image.
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

# test job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Linter and Test
      run: ./gradlew check
    - name: Upload Reports
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Test-Reports
        path: app/build/reports

# deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: '1.1.0'
        version-fragment: 'feature'
    - name: Bumped Release Version
      run: echo ${{ steps.bump_version.outputs.next-version }}
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        image: mansisinghdocker/demo-ci-cd
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "GithubCICD-v-${{ steps.bump_version.outputs.next-version }}"

# job to run tests on emulator
  run-ui-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run UI test
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
        api-level: 29
        script: ./gradlew connectedDebugAndroidTest
    - name: Upload UI test reports
      uses: actions/upload-artifact@v3.1.2
      with:
        name: UI-Test-reports
        path: app/build/reports
