name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # deploy image on docker hub with minor release
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: '2.0.0'
          # changing minor semantic version
          version-fragment: 'feature'
      - name: Bumped Release Version
        run: echo ${{ steps.bump_version.outputs.next-version }}
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: mansisinghdocker/demo-ci-cd
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "GithubCICD-v-${{ steps.bump_version.outputs.next-version }}"

  # Checkout main branch and build the APK
  build-main:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Master APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-master.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk_master
          path: app/build/outputs/apk/debug/app-master.apk

  # Checkout PR branch and build the APK
  build-pr:
    runs-on: macOS-latest
    needs: build-main
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build PR APK
        run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-pr.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk_pr
          path: app/build/outputs/apk/debug/app-pr.apk

  apk-diff:
    needs: [ build-main, build-pr ]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install diffuse
        run: brew install JakeWharton/repo/diffuse
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: apk_master
          path: app/build/outputs/apk/debug/app-master
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: apk_pr
          path: app/build/outputs/apk/debug/app-pr
      - name: run differ
        run: diffuse diff app/build/outputs/apk/debug/app-master/app-master.apk app/build/outputs/apk/debug/app-pr/app-pr.apk
